### ISSUE TITLE
gipeda.js doesn't show all benchmarks

### ISSUE THREAD

**Issue by sgraf812** [nomeata/gipeda#41]
e.g. https://github.com/sgraf812/gpn should define 5 benchmarks, all of which are transformed in the expected way by gipeda (the Haskell part). But when checking their #all page, there is no mention of any older commit than the most recent. Also when on the #graphs page, only the 'gulasch' benchmark is shown, probably because it's the only one with a change during the 4 commits.

So, to reproduce:
1. Install the HEAD of feed-gipeda: `$ git clone https://github.com/sgraf812/feed-gipeda && cd feed-gipeda && stack install`
2. Install the HEAD of gipeda (...)
3. Have `feed-gipeda.yaml` like below (including it in the list breaks Markdown formatting)
4. `$ feed-gipeda --config=./feed-gipeda.yaml --deploy-to=./gpn --watch=3600` and wait about 10 s
5. `$ python3 -m http.server`
6. Visit http://localhost:8000/sgraf812/gpn/#graphs and http://localhost:8000/sgraf812/gpn/#all
7. Also notice that e.g. http://localhost:8000/sgraf812/gpn/#graph/tschunk works as expected, so it's only a matter of displaying the links.

```
$ cat > feed-gipeda.yaml
repositories:
- https://github.com/sgraf812/gpn
```

That _might_ have to do with e9dc0850af448513d1b59727291a24ca5325ff2c, but I'm not sure.

Also, the generated `gipeda.yaml` for which gipeda is then executed:

```
interestingBranches: ! '*'
diffLink: ! '{{rev}}{{base}}'
start: 4acfa7637c89544f742884e32e1566e7c27c9657
benchmarks:
- threshold: 1
  smallerIsBetter: false
  type: small integral
  match: ! '*'
- group: Build
  smallerIsBetter: false
  type: small integral
  match: build/warnings
  important: false
interestingTags: ! '*'
revisionInfo: <a href="https://github.com/sgraf812/gpn/commit/{{rev}}>View Diff</a>
benchmarkScript: cat ./stats.txt
title: gpn
limitRecent: 20
```
